# === build_release.yaml  ==============================================================================================
#                                               Sen Infrastructure
#                   Released under the Apache License v2.0 (SPDX-License-Identifier Apache-2.0).
#                                    See the LICENSE.txt file for more information.
#                   © Airbus SAS, Airbus Helicopters, and Airbus Defence and Space SAU/GmbH/SAS.
# ======================================================================================================================

name: Build release

on:
  push:
    branches:
      - feat/release-workflow

jobs:
  compute-matrix-jobs:
    name: "Generate build matrix"
    runs-on: ubuntu-latest
    outputs:
      jobs: ${{ steps.compute-jobs.outputs.jobs }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - id: compute-jobs
        run: python .github/scripts/generate_matrix_jobs.py --release
  create_release_with_artifacts:
    name: "Build Job: ${{ matrix.compiler.name }}-${{ matrix.compiler.version }} C++${{ matrix.std }} [${{ matrix.build_type }}]"
    needs: compute-matrix-jobs
    runs-on: self-hosted
    strategy:
      fail-fast: true
      matrix:
        include: ${{ fromJson(needs.compute-matrix-jobs.outputs.jobs) }}
    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: Install gcc-${{ matrix.compiler.version }}
        if: matrix.compiler.name == 'gcc'
        shell: bash
        run: sudo apt-get install -y g++-${{ matrix.compiler.version }}

      - name: Install pip dependencies
        run: |
          pip install conan pytest

      - name: Setup conan profile
        shell: bash
        run: |
          rm ~/.conan2/profiles/default
          conan profile detect --force -vquiet
          cp .conan/profiles/sen_gcc ~/.conan2/profiles/default
          echo tools.system.package_manager:mode=install >> ~/.conan2/profiles/default
          echo tools.system.package_manager:sudo=True >> ~/.conan2/profiles/default
          sed -i '/^\[options\]$/i doxygen*:compiler.cppstd=20' ~/.conan2/profiles/default
          sed -i '/^\[tool_requires\]$/a &:doxygen/[>=1.15.0]' ~/.conan2/profiles/default
          conan profile show -pr default

      - name: Install system dependencies
        # need for clang compat with sdl2 2.24.0
        shell: bash
        run: sudo apt-get install -y libxext-dev

      - name: Auto generate docs
        run: |
          conan install . --build=missing
          cmake --preset=conan-gcc-release
          cmake --build build/gcc/Release/
          cmake --build build/gcc/Release/ --target package

      - name: test
        run: |
          file build/clang/Release/sen-latest-x86_64-linux-clang-22.0.0-release.tar.gz
          la build/clang/Release/sen-latest-x86_64-linux-clang-22.0.0-release.tar.gz
